"""empty message

Revision ID: 0f0c0cfd7e61
Revises: df5a25c003df
Create Date: 2022-06-06 22:03:39.799214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0c0cfd7e61'
down_revision = 'df5a25c003df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('created', sa.String(length=80), nullable=False))
    op.add_column('people', sa.Column('edited', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'edited')
    op.drop_column('people', 'created')
    # ### end Alembic commands ###
