"""empty message

Revision ID: 20d9e4292cd3
Revises: 8838aa3a5e85
Create Date: 2022-06-07 00:02:14.664304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d9e4292cd3'
down_revision = '8838aa3a5e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('_id', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', '_id')
    # ### end Alembic commands ###
