"""empty message

Revision ID: 26c11d927b94
Revises: 582836492c26
Create Date: 2022-06-06 22:06:38.021476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c11d927b94'
down_revision = '582836492c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('description', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'description')
    # ### end Alembic commands ###
