"""empty message

Revision ID: 2f2a1a578fd3
Revises: 26c11d927b94
Create Date: 2022-06-06 22:07:11.586332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2a1a578fd3'
down_revision = '26c11d927b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('uid', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'uid')
    # ### end Alembic commands ###
