"""empty message

Revision ID: 582836492c26
Revises: 0f0c0cfd7e61
Create Date: 2022-06-06 22:05:54.805114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582836492c26'
down_revision = '0f0c0cfd7e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld', sa.String(length=150), nullable=False))
    op.add_column('people', sa.Column('url', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'url')
    op.drop_column('people', 'homeworld')
    # ### end Alembic commands ###
