"""empty message

Revision ID: 8838aa3a5e85
Revises: 0b0e251b59fc
Create Date: 2022-06-07 00:01:04.187886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8838aa3a5e85'
down_revision = '0b0e251b59fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('people', 'uid',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_column('people', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('_id', mysql.VARCHAR(length=150), nullable=False))
    op.alter_column('people', 'uid',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('people', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
